export const SUBMIT_PRICE_REQUEST = "SUBMIT_PRICE_REQUEST";
export const SUBMIT_PRICE_SUCCESS = "SUBMIT_PRICE_SUCCESS";
export const SUBMIT_PRICE_FAILURE = "SUBMIT_PRICE_FAILURE";

export const FETCH_PENDING_PRICES = "FETCH_PENDING_PRICES";
export const FETCH_PENDING_SUCCESS = "FETCH_PENDING_SUCCESS";
export const FETCH_PENDING_FAILURE = "FETCH_PENDING_FAILURE";

export const APPROVE_REJECT_PRICE = "APPROVE_REJECT_PRICE";
export const APPROVE_REJECT_SUCCESS = "APPROVE_REJECT_SUCCESS";
export const APPROVE_REJECT_FAILURE = "APPROVE_REJECT_FAILURE";
